language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - 10

jobs:
  include:
    - stage: test
      script:
       - npm ci && npm run lint
    - stage: build
      script:
       - npm ci && npm run build
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
          
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
